-- Create the attendance logs table to store data received from the biometric device
CREATE TABLE IF NOT EXISTS public.attendance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid BIGINT NOT NULL, -- The unique ID of the log record from the device
    employee_name TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT NOT NULL, -- e.g., 'present', 'absent', 'late'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure RLS is enabled for security (optional but recommended)
ALTER TABLE public.attendance_logs ENABLE ROW LEVEL SECURITY;

-- Allow read access for authenticated users (the React app)
CREATE POLICY "Allow read access to authenticated users" 
ON public.attendance_logs 
FOR SELECT 
TO authenticated 
USING (true);

-- Allow insert access for service_role (the Node.js script)
CREATE POLICY "Allow insert access to service_role" 
ON public.attendance_logs 
FOR INSERT 
TO service_role 
WITH CHECK (true);
